changelog:
  categories:
    - title: 💥 Breaking Changes
      labels:
        - Semver-Major
    - title: 🛠️ Improvements
      labels:
        - Semver-Minor
    - title: 🪲 Bug Fixes
      labels:
        - Semver-Patch
    - title: 🤔 Unlabeled
        - "*"
