# This workflow will be triggered by a GitHub pull-request.
---
name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run script
        run: node index.js
